name = "CaliforniaBightNitrate"
uuid = "5797ec1b-cad6-4e8e-9d6b-196a0ab7697f"
authors = ["Jago Strong-Wright <jagoosw@protonmail.com>"]
version = "0.1.0"

[deps]
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"

[compat]
Artifacts = "1.10"
Interpolations = "0.15"
JLD2 = "0.5"
